### ISSUE TITLE
GT CEu Modern showing both durability bar and percentage

### ISSUE THREAD

**Issue by Svetrikk** [Leclowndu93150/DuraDisplay#7]
Items with durability from GT CEu Modern shows both vanilla durability bar and percentage from this mod

MC Version: 1.20.1
Mod version: 1.0.3
Forge version: 47.3.0
GT CEu Modern version: 1.4.4

![image](https://github.com/user-attachments/assets/41062624-f0df-4efa-9bec-2ea9a20fe61c)

**Comment by Leclowndu93150** [comment]
We have no support for GregTech in 1.20.1 

If you can find someone willing to add the compat using a pull request we would gladly merge it
